sudo: required
services:
  - docker

before_install:
  - docker build -t salemhusseini/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true salemhusseini/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-841128099044"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
