sudo: required
services:
  - docker

before_install:
  - docker build -t salemhusseini/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true salemhusseini/docker-react npm run test -- --coverage
